CREATE DATABASE IF NOT EXISTS quad_sync;
USE quad_sync;

CREATE TABLE IF NOT EXISTS quad_sync (
  token VARCHAR(128) NOT NULL,
  device_id VARCHAR(128) NOT NULL,
  snapshot LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX IF NOT EXISTS idx_quad_sync_updated_at ON quad_sync(updated_at);
